# Reload tmux config with Ctrl-B then r
bind r source-file ~/.tmux.conf

################
# Tmux Plugins #
################
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
